version: '3'

services:
  database:
    image: mariadb:10.11.2
    environment:
      MYSQL_DATABASE: qatests
      MYSQL_USER: root
      MYSQL_PASSWORD: NotRoot2023
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  database_data: